package userinterface.AdministrativeCampRole;

import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Organization.NurseOrganization;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Network.Network;


/**
 *
 * @author anirudhnegi
 *
 **/
public class AdminWorkCampAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;
    EcoSystem ecosystem;
    Network network;
    NurseOrganization organization;

    
        public AdminWorkCampAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount account,Network network,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.ecosystem = ecosystem;
        this.network = network;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageEmpButton = new javax.swing.JButton();
        manageOrgButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        VolunteerApprovalBtn = new javax.swing.JButton();
        ManageUserBtn = new javax.swing.JButton();
        HealthCampBtn = new javax.swing.JButton();
        NurseEnrollment = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(181, 223, 237));
        setPreferredSize(new java.awt.Dimension(1546, 471));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                             MAIN MENU");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 40, 500, -1));

        manageEmpButton.setText("MANAGE EMPLOYEE");
        manageEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmpButtonActionPerformed(evt);
            }
        });
        add(manageEmpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 270, 40));

        manageOrgButton.setText("MANAGE ORGANIZATION");
        manageOrgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrgButtonActionPerformed(evt);
            }
        });
        add(manageOrgButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 270, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        enterpriseLabel.setText("HEALTHCAMP NAME:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 240, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 390, 30));

        VolunteerApprovalBtn.setText("VOLUNTEER APPROVAL");
        VolunteerApprovalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolunteerApprovalBtnActionPerformed(evt);
            }
        });
        add(VolunteerApprovalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 270, 40));

        ManageUserBtn.setText("MANAGE USER");
        ManageUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserBtnActionPerformed(evt);
            }
        });
        add(ManageUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 270, 40));

        HealthCampBtn.setText("HEALTH CAMP REQUEST");
        HealthCampBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HealthCampBtnActionPerformed(evt);
            }
        });
        add(HealthCampBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 270, 40));

        NurseEnrollment.setText("NURSE ENROLLMENT ");
        NurseEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NurseEnrollmentActionPerformed(evt);
            }
        });
        add(NurseEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 280, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void manageEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmpButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmpButtonActionPerformed

    private void manageOrgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrgButtonActionPerformed
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrgButtonActionPerformed

    private void VolunteerApprovalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolunteerApprovalBtnActionPerformed
        // TODO add your handling code here:
        VolunteerCampApprovalJPanel volunteerApprovalJPanel = new VolunteerCampApprovalJPanel(userProcessContainer, enterprise, account);
        userProcessContainer.add("VolunteerApprovalJPanel", volunteerApprovalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_VolunteerApprovalBtnActionPerformed

    private void ManageUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserBtnActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", manageUserAccountJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageUserBtnActionPerformed

    private void HealthCampBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HealthCampBtnActionPerformed
        // TODO add your handling code here:
        HealthcampRequestJPanel HealthcampRequestJPanel = new HealthcampRequestJPanel(userProcessContainer, account, ecosystem,network,enterprise);
        userProcessContainer.add("HealthcampRequestJPanel", HealthcampRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_HealthCampBtnActionPerformed

    private void NurseEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseEnrollmentActionPerformed
        // TODO add your handling code here:
        NurseEnterpriseChooserJPanel NurseEnterpriseChooserJPanel = new NurseEnterpriseChooserJPanel(userProcessContainer,  account,  organization,  enterprise, ecosystem);
        userProcessContainer.add("NurseEnterpriseChooserJPanel", NurseEnterpriseChooserJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_NurseEnrollmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HealthCampBtn;
    private javax.swing.JButton ManageUserBtn;
    private javax.swing.JToggleButton NurseEnrollment;
    private javax.swing.JButton VolunteerApprovalBtn;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageEmpButton;
    private javax.swing.JButton manageOrgButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
